locals { all_vms=merge({for k,v in var.web_vms:k=>merge(v,{role="web",data_disks={}})},{for k,v in var.was_vms:k=>merge(v,{role="was"})}) }
data "azurerm_subnet" "vm" { for_each=local.all_vms name=each.value.subnet_name virtual_network_name=var.vnet_name resource_group_name=var.vnet_resource_group_name }
data "azurerm_subnet" "lb" { count=var.internal_lb.enabled?1:0 name=var.internal_lb.subnet_name virtual_network_name=var.vnet_name resource_group_name=var.vnet_resource_group_name }
resource "azurerm_network_interface" "vm" { for_each=local.all_vms name="nic-${each.value.name}" location=var.location resource_group_name=var.resource_group_name ip_configuration { name="ipconfig1" subnet_id=data.azurerm_subnet.vm[each.key].id private_ip_address_allocation="Static" private_ip_address=each.value.private_ip_address } tags=merge(var.tags,{role=each.value.role,hostname=each.value.name,private_ip=each.value.private_ip_address}) }
resource "azurerm_linux_virtual_machine" "vm" { for_each=local.all_vms name=each.value.name location=var.location resource_group_name=var.resource_group_name size=each.value.vm_size admin_username=var.admin_username network_interface_ids=[azurerm_network_interface.vm[each.key].id] disable_password_authentication=true admin_ssh_key { username=var.admin_username public_key=var.ssh_public_key } os_disk { name="osdisk-${each.value.name}" caching="ReadWrite" storage_account_type=var.os_disk_storage_type disk_size_gb=each.value.os_disk_size_gb } source_image_reference { publisher=var.image_publisher offer=var.image_offer sku=var.image_sku version=var.image_version } tags=merge(var.tags,{role=each.value.role,hostname=each.value.name,private_ip=each.value.private_ip_address}) }
locals { data_disks_flat=merge([for vm_key,vm in var.was_vms:{for disk_key,disk in vm.data_disks:"${vm_key}-${disk_key}"=>{vm_key=vm_key,disk_key=disk_key,vm_name=vm.name,name="disk-${vm.name}-${disk_key}",size_gb=disk.size_gb,storage_account_type=disk.storage_account_type,lun=disk.lun,caching=disk.caching}}]...) }
resource "azurerm_managed_disk" "data" { for_each=local.data_disks_flat name=each.value.name location=var.location resource_group_name=var.resource_group_name storage_account_type=each.value.storage_account_type create_option="Empty" disk_size_gb=each.value.size_gb tags=merge(var.tags,{role="was",hostname=each.value.vm_name,disk_role=each.value.disk_key}) }
resource "azurerm_virtual_machine_data_disk_attachment" "data" { for_each=local.data_disks_flat managed_disk_id=azurerm_managed_disk.data[each.key].id virtual_machine_id=azurerm_linux_virtual_machine.vm[each.value.vm_key].id lun=each.value.lun caching=each.value.caching }
resource "azurerm_lb" "internal" { count=var.internal_lb.enabled?1:0 name=var.internal_lb.name location=var.location resource_group_name=var.resource_group_name sku="Standard" frontend_ip_configuration { name=var.internal_lb.frontend_ip_name subnet_id=data.azurerm_subnet.lb[0].id private_ip_address_allocation="Static" private_ip_address=var.internal_lb.frontend_private_ip } tags=var.tags }
resource "azurerm_lb_backend_address_pool" "web" { count=var.internal_lb.enabled?1:0 loadbalancer_id=azurerm_lb.internal[0].id name="be-web" }
resource "azurerm_network_interface_backend_address_pool_association" "web" { for_each=var.internal_lb.enabled?var.web_vms:{} network_interface_id=azurerm_network_interface.vm[each.key].id ip_configuration_name="ipconfig1" backend_address_pool_id=azurerm_lb_backend_address_pool.web[0].id }
resource "azurerm_lb_probe" "web" { count=var.internal_lb.enabled?1:0 loadbalancer_id=azurerm_lb.internal[0].id name="probe-web" protocol="Tcp" port=var.internal_lb.probe_port }
resource "azurerm_lb_rule" "web" { count=var.internal_lb.enabled?1:0 loadbalancer_id=azurerm_lb.internal[0].id name="rule-web" protocol="Tcp" frontend_port=var.internal_lb.lb_rule_port backend_port=var.internal_lb.backend_port frontend_ip_configuration_name=var.internal_lb.frontend_ip_name backend_address_pool_ids=[azurerm_lb_backend_address_pool.web[0].id] probe_id=azurerm_lb_probe.web[0].id }
resource "local_file" "ansible_inventory" { filename="${path.module}/ansible_inventory.ini" content=join("
",concat(["[web]"],[for k,vm in var.web_vms:"${vm.name} ansible_host=${vm.private_ip_address}"],[""],["[was]"],[for k,vm in var.was_vms:"${vm.name} ansible_host=${vm.private_ip_address}"],[""],["[all:vars]"],["ansible_user=${var.admin_username}"])) }
