data "azurerm_subnet" "pe" { name=var.private_endpoint_subnet_name virtual_network_name=var.vnet_name resource_group_name=var.vnet_resource_group_name }
data "azurerm_private_dns_zone" "openai" { name=var.private_dns_zones.openai resource_group_name=var.private_dns_zone_resource_group_name }
data "azurerm_private_dns_zone" "search" { name=var.private_dns_zones.search resource_group_name=var.private_dns_zone_resource_group_name }
data "azurerm_private_dns_zone" "blob" { name=var.private_dns_zones.blob resource_group_name=var.private_dns_zone_resource_group_name }
data "azurerm_private_dns_zone" "keyvault" { name=var.private_dns_zones.keyvault resource_group_name=var.private_dns_zone_resource_group_name }
resource "azurerm_cognitive_account" "openai" { count=var.openai.enabled?1:0 name=var.openai.name location=var.location resource_group_name=var.resource_group_name kind="OpenAI" sku_name=var.openai.sku_name public_network_access_enabled=var.openai.public_network_access=="Enabled" custom_subdomain_name=try(var.openai.custom_subdomain_name,null) tags=merge(var.tags,{service="azure-openai"}) }
resource "azurerm_search_service" "search" { count=var.search.enabled?1:0 name=var.search.name resource_group_name=var.resource_group_name location=var.location sku=var.search.sku replica_count=var.search.replica_count partition_count=var.search.partition_count public_network_access_enabled=var.search.public_network_access=="Enabled" tags=merge(var.tags,{service="ai-search"}) }
resource "azurerm_storage_account" "storage" { count=var.storage.enabled?1:0 name=var.storage.name resource_group_name=var.resource_group_name location=var.location account_tier=var.storage.account_tier account_replication_type=var.storage.account_replication_type public_network_access_enabled=var.storage.public_network_access=="Enabled" allow_nested_items_to_be_public=var.storage.allow_blob_public_access network_rules { default_action=var.storage.default_action bypass=["AzureServices"] } tags=merge(var.tags,{service="storage"}) }
resource "azurerm_storage_container" "containers" { for_each=var.storage.enabled?toset(var.storage.containers):toset([]) name=each.key storage_account_name=azurerm_storage_account.storage[0].name container_access_type="private" }
resource "azurerm_key_vault" "kv" { count=var.keyvault.enabled?1:0 name=var.keyvault.name location=var.location resource_group_name=var.resource_group_name tenant_id=var.keyvault.tenant_id sku_name=var.keyvault.sku_name public_network_access_enabled=var.keyvault.public_network_access=="Enabled" purge_protection_enabled=var.keyvault.purge_protection enable_rbac_authorization=true tags=merge(var.tags,{service="key-vault"}) }
resource "azurerm_private_endpoint" "openai" { count=var.openai.enabled&&var.private_endpoints.openai?1:0 name="pe-${var.openai.name}" location=var.location resource_group_name=var.resource_group_name subnet_id=data.azurerm_subnet.pe.id private_service_connection { name="psc-${var.openai.name}" private_connection_resource_id=azurerm_cognitive_account.openai[0].id is_manual_connection=false subresource_names=["account"] } private_dns_zone_group { name="default" private_dns_zone_ids=[data.azurerm_private_dns_zone.openai.id] } tags=var.tags }
resource "azurerm_private_endpoint" "search" { count=var.search.enabled&&var.private_endpoints.search?1:0 name="pe-${var.search.name}" location=var.location resource_group_name=var.resource_group_name subnet_id=data.azurerm_subnet.pe.id private_service_connection { name="psc-${var.search.name}" private_connection_resource_id=azurerm_search_service.search[0].id is_manual_connection=false subresource_names=["searchService"] } private_dns_zone_group { name="default" private_dns_zone_ids=[data.azurerm_private_dns_zone.search.id] } tags=var.tags }
resource "azurerm_private_endpoint" "blob" { count=var.storage.enabled&&var.private_endpoints.blob?1:0 name="pe-${var.storage.name}-blob" location=var.location resource_group_name=var.resource_group_name subnet_id=data.azurerm_subnet.pe.id private_service_connection { name="psc-${var.storage.name}-blob" private_connection_resource_id=azurerm_storage_account.storage[0].id is_manual_connection=false subresource_names=["blob"] } private_dns_zone_group { name="default" private_dns_zone_ids=[data.azurerm_private_dns_zone.blob.id] } tags=var.tags }
resource "azurerm_private_endpoint" "keyvault" { count=var.keyvault.enabled&&var.private_endpoints.keyvault?1:0 name="pe-${var.keyvault.name}" location=var.location resource_group_name=var.resource_group_name subnet_id=data.azurerm_subnet.pe.id private_service_connection { name="psc-${var.keyvault.name}" private_connection_resource_id=azurerm_key_vault.kv[0].id is_manual_connection=false subresource_names=["vault"] } private_dns_zone_group { name="default" private_dns_zone_ids=[data.azurerm_private_dns_zone.keyvault.id] } tags=var.tags }
